project:
  type: website

execute:
  freeze: auto

website:
  title: "Quarto Parallax"
  site-url: "https://kevolve.github.io/quarto-parallax"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - text: "{{< iconify fa6-brands researchgate >}}"
        href: "https://www.researchgate.net/profile/Kevin-Bairos-Novak/"
      - text: "{{< iconify fa6-brands github >}}"
        href: "https://github.com/kevolve/"
  page-footer:
    left: "&copy; Kevin R. Bairos-Novak, 2024"

format:
  html:
    theme: minty
    css: style.css
    toc: true
    include-before-body: header.html

editor: source

